SELECT * FROM PACKAGES;
-- TABLE INFOS



-- -------------------------------------------------------

-- CUST_ID MSISDN convertion procedure
CREATE PROCEDURE MSISDN_BY_ID
AS
SELECT PACKAGE_ID 
    FROM BALANCE 
    WHERE CUST_ID = (
        SELECT CUST_ID
        FROM CUSTOMER
        WHERE MSISDN = ?);
-- subprocedure denemesi
CREATE PROCEDURE SHOW_AMOUNT_DATA
AS 
SELECT AMOUNT_DATA 
FROM PACKAGE 
WHERE PACKAGE_ID = MSISDN_BY_ID(?);

-- -------------------------------------------------------



--PROCEDURE TEMPLATE
CREATE PROCEDURE PROC1 
AS
SELECT * FROM BALANCE;

-- SHOW_BALANCE
CREATE PROCEDURE BALANCE_SHOW
SELECT BAL_LVL_MINUTES,BAL_LVL_SMS,BAL_LVL_DATA
FROM SHOW_BALANCE
WHERE CUST_ID = ?;

-- GET PRICE BY MSISDN
CREATE PROCEDURE SHOW_PRICE 
AS
SELECT PRICE 
FROM PACKAGE 
WHERE PACKAGE_ID = (
    SELECT PACKAGE_ID 
    FROM BALANCE 
    WHERE CUST_ID = (
        SELECT CUST_ID 
        FROM CUSTOMER 
        WHERE MSISDN = ?
    )
);

-- GET AMOUNT DATA BY MSISDN
CREATE PROCEDURE SHOW_AMOUNT_DATA 
AS
SELECT AMOUNT_DATA 
FROM PACKAGE 
WHERE PACKAGE_ID = (
    SELECT PACKAGE_ID 
    FROM BALANCE 
    WHERE CUST_ID = (
        SELECT CUST_ID 
        FROM CUSTOMER 
        WHERE MSISDN = ?
    )
);

-- GET AMOUNT MINUTES BY MSISDN
CREATE PROCEDURE SHOW_AMOUNT_MINUTES
AS
SELECT AMOUNT_MINUTES 
FROM PACKAGE 
WHERE PACKAGE_ID = (
    SELECT PACKAGE_ID 
    FROM BALANCE 
    WHERE CUST_ID = (
        SELECT CUST_ID 
        FROM CUSTOMER 
        WHERE MSISDN = ?
    )
);

-- GET AMOUNT SMS BY MSISDN
CREATE PROCEDURE SHOW_AMOUNT_SMS 
AS
SELECT AMOUNT_SMS
FROM PACKAGE 
WHERE PACKAGE_ID = (
    SELECT PACKAGE_ID 
    FROM BALANCE 
    WHERE CUST_ID = (
        SELECT CUST_ID 
        FROM CUSTOMER 
        WHERE MSISDN = ?
    )
);




-- KAAN İÇİN

-- GET PACKAGE_NAME BY MSISDN
CREATE PROCEDURE GET_PACKAGE_NAME_BY_MSISDN
AS
SELECT PACKAGE_NAME  
FROM PACKAGE 
WHERE PACKAGE_ID = (
    SELECT PACKAGE_ID 
    FROM BALANCE 
    WHERE CUST_ID = (
        SELECT CUST_ID 
        FROM CUSTOMER 
        WHERE MSISDN = ?
    )
);

-- GET CUSTOMER INFO BY MSISDN
CREATE PROCEDURE  GET_CUSTOMER_INFO_BY_MSISDN 
AS
SELECT CUST_ID, MSISDN, NAME, SURNAME, EMAIL, SDATE, TC_NO
FROM CUSTOMER
WHERE MSISDN = ?;


-- UPDATE AMOUNT_DATA_BY_MSISDN
CREATE PROCEDURE UPDATE_CUSTOMER_AMOUNT_DATA_BY_MSISDN
AS
UPDATE BALANCE 
SET BAL_LVL_DATA = BAL_LVL_DATA - ?
WHERE CUST_ID = (
    SELECT CUST_ID 
    FROM CUSTOMER 
    WHERE MSISDN = ?
);


-- GET PACKAGE_NAME_BY_PACKAGE_ID
CREATE PROCEDURE GET_PACKAGE_NAME_BY_PACKAGE_ID
AS
SELECT PACKAGE_NAME 
FROM PACKAGE
WHERE PACKAGE_ID = ?;


-- GET PACKAGE_ID_BY_PACKAGE_NAME
CREATE PROCEDURE GET_PACKAGE_ID_BY_PACKAGE_NAME
AS
SELECT PACKAGE_ID 
FROM PACKAGE
WHERE PACKAGE_NAME = ?;


-- GET MAX CUSTOMER ID 
CREATE PROCEDURE GET_MAX_CUSTOMER_ID 
AS
SELECT MAX(CUST_ID) AS MAX_CUST_ID 
FROM CUSTOMER;


-- GET MAX BALANCE ID 
CREATE PROCEDURE GET_MAX_BALANCE_ID 
AS
SELECT MAX(BALANCE_ID) AS MAX_BALANCE_ID 
FROM BALANCE;


-- INSERT BALANCE TO CUSTOMER
CREATE PROCEDURE INSERT_BALANCE_TO_CUSTOMER 
AS 
INSERT INTO BALANCE (BALANCE_ID, CUST_ID, PACKAGE_ID, BAL_LVL_MINUTES, BAL_LVL_SMS, BAL_LVL_DATA, SDATE, EDATE)
VALUES (?, ?, ?, ?, ?, ?, ?, ?);


CREATE PROCEDURE INSERT_NEW_CUSTOMER
AS
INSERT INTO CUSTOMER (CUST_ID, NAME, SURNAME, MSISDN, EMAIL, PASSWORD, SDATE, TC_NO) 
VALUES (?, ?, ?, ?, ?, ?, ?, ?);



-- KENAN İÇİN

-- GET PACKAGE NAME BY MSISDN
CREATE PROCEDURE GET_PACKAGE_NAME_BY_MSISDN
AS
SELECT PACKAGE_NAME  
FROM PACKAGE 
WHERE PACKAGE_ID = (
    SELECT PACKAGE_ID 
    FROM BALANCE 
    WHERE CUST_ID = (
        SELECT CUST_ID 
        FROM CUSTOMER 
        WHERE MSISDN = ?
    )
);

-- GET CUSTOMER ID BY MSISDN
CREATE PROCEDURE GET_CUSTOMER_ID_BY_MSISDN
AS
SELECT CUST_ID 
FROM CUSTOMER 
WHERE MSISDN = ?;

-- GET AMOUNT MINUTES BY MSISDN
CREATE PROCEDURE GET_CUSTOMER_AMOUNT_MINUTES_BY_MSISDN
AS
SELECT BAL_LVL_MINUTES
FROM BALANCE
WHERE CUST_ID = (
    SELECT CUST_ID 
    FROM CUSTOMER 
    WHERE MSISDN = ?
);

-- UPDATE AMOUNT MINUTES BY MSISDN
CREATE PROCEDURE UPDATE_CUSTOMER_AMOUNT_MINUTES_BY_MSISDN
AS
UPDATE BALANCE 
SET BAL_LVL_MINUTES = BAL_LVL_MINUTES - ?
WHERE CUST_ID = (
    SELECT CUST_ID 
    FROM CUSTOMER 
    WHERE MSISDN = ?
);

-- GET AMOUNT SMS BY MSISDN
CREATE PROCEDURE GET_CUSTOMER_AMOUNT_SMS_BY_MSISDN
AS
SELECT BAL_LVL_SMS
FROM BALANCE
WHERE CUST_ID = (
    SELECT CUST_ID 
    FROM CUSTOMER 
    WHERE MSISDN = ?
);

-- UPDATE AMOUNT SMS BY MSISDN
CREATE PROCEDURE UPDATE_CUSTOMER_AMOUNT_SMS_BY_MSISDN
AS
UPDATE BALANCE 
SET BAL_LVL_SMS = BAL_LVL_SMS - ?
WHERE CUST_ID = (
    SELECT CUST_ID 
    FROM CUSTOMER 
    WHERE MSISDN = ?
);

-- GET AMOUNT DATA BY MSISDN
CREATE PROCEDURE GET_CUSTOMER_AMOUNT_DATA_BY_MSISDN
AS
SELECT BAL_LVL_DATA
FROM BALANCE
WHERE CUST_ID = (
    SELECT CUST_ID 
    FROM CUSTOMER 
    WHERE MSISDN = ?
);

-- UPDATE AMOUNT DATA BY MSISDN
CREATE PROCEDURE UPDATE_CUSTOMER_AMOUNT_DATA_BY_MSISDN
AS
UPDATE BALANCE 
SET BAL_LVL_DATA = BAL_LVL_DATA - ?
WHERE CUST_ID = (
    SELECT CUST_ID 
    FROM CUSTOMER 
    WHERE MSISDN = ?
);

-- GET_PACKAGE_INFO_BY_MSISDN
CREATE PROCEDURE GET_PACKAGE_INFO_BY_MSISDN
AS
SELECT *  
FROM PACKAGE 
WHERE PACKAGE_ID = (
    SELECT PACKAGE_ID 
    FROM BALANCE 
    WHERE CUST_ID = (
        SELECT CUST_ID 
        FROM CUSTOMER 
        WHERE MSISDN = ?
    )
);

-- GET_CUSTOMER_EMAIL_BY_MSISDN
CREATE PROCEDURE GET_CUSTOMER_EMAIL_BY_MSISDN
AS
SELECT EMAIL 
FROM CUSTOMER 
WHERE MSISDN = ?;

-- GET_CUSTOMER_NAME_BY_MSISDN
CREATE PROCEDURE GET_CUSTOMER_NAME_BY_MSISDN
AS
SELECT NAME 
FROM CUSTOMER 
WHERE MSISDN = ?;

-- GET_CUSTOMER_SURNAME_BY_MSISDN
CREATE PROCEDURE GET_CUSTOMER_SURNAME_BY_MSISDN
AS
SELECT SURNAME 
FROM CUSTOMER 
WHERE MSISDN = ?;

