package com.i2i.aom.constant;

public class OracleQueries {
    public final static String SELECT_ALL_PACKAGES = "SELECT PACKAGE_ID,PACKAGE_NAME,PRICE,AMOUNT_MINUTES,AMOUNT_DATA,AMOUNT_SMS,PERIOD FROM PACKAGE";
    public final static String SELECT_PACKAGE_DETAILS_NAME = "SELECT AMOUNT_MINUTES, AMOUNT_SMS, AMOUNT_DATA FROM PACKAGE WHERE PACKAGE_NAME = ?";
    public final static String SELECT_PACKAGE_ID = "SELECT PACKAGE_ID FROM PACKAGE WHERE PACKAGE_NAME = ?";
    public final static String SELECT_PACKAGE_DETAILS_ID = "SELECT AMOUNT_MINUTES, AMOUNT_SMS, AMOUNT_DATA, PERIOD FROM PACKAGE WHERE PACKAGE_ID = ?";
    public final static String GET_ALL_CUSTOMERS = "SELECT CUST_ID,MSISDN,NAME,SURNAME,EMAIL,SDATE,TC_NO FROM CUSTOMER";
    public final static String INSERT_BALANCE_TO_CUSTOMER = "INSERT INTO BALANCE (BALANCE_ID, CUST_ID, PACKAGE_ID, BAL_LVL_MINUTES, BAL_LVL_SMS, BAL_LVL_DATA, SDATE, EDATE) " +
            "VALUES (balance_id_sequence.NEXTVAL, ?, ?, ?, ?, ?, ?, ?)";

}
