SELECT * FROM PACKAGES;
-- TABLE INFOS



-- -------------------------------------------------------

-- CUST_ID MSISDN convertion procedure
CREATE PROCEDURE MSISDN_BY_ID
AS
SELECT PACKAGE_ID 
    FROM BALANCE 
    WHERE CUST_ID = (
        SELECT CUST_ID
        FROM CUSTOMER
        WHERE MSISDN = ?);
-- subprocedure denemesi
CREATE PROCEDURE SHOW_AMOUNT_DATA
AS 
SELECT AMOUNT_DATA 
FROM PACKAGE 
WHERE PACKAGE_ID = MSISDN_BY_ID(?);

-- -------------------------------------------------------



--PROCEDURE TEMPLATE
CREATE PROCEDURE PROC1 
AS
SELECT * FROM BALANCE;

-- SHOW_BALANCE
CREATE PROCEDURE BALANCE_SHOW
SELECT BAL_LVL_MINUTES,BAL_LVL_SMS,BAL_LVL_DATA
FROM SHOW_BALANCE
WHERE CUST_ID = ?;

-- GET PRICE BY MSISDN
CREATE PROCEDURE SHOW_PRICE 
AS
SELECT PRICE 
FROM PACKAGE 
WHERE PACKAGE_ID = (
    SELECT PACKAGE_ID 
    FROM BALANCE 
    WHERE CUST_ID = (
        SELECT CUST_ID 
        FROM CUSTOMER 
        WHERE MSISDN = ?
    )
);

-- GET AMOUNT DATA BY MSISDN
CREATE PROCEDURE SHOW_AMOUNT_DATA 
AS
SELECT AMOUNT_DATA 
FROM PACKAGE 
WHERE PACKAGE_ID = (
    SELECT PACKAGE_ID 
    FROM BALANCE 
    WHERE CUST_ID = (
        SELECT CUST_ID 
        FROM CUSTOMER 
        WHERE MSISDN = ?
    )
);

-- GET AMOUNT MINUTES BY MSISDN
CREATE PROCEDURE SHOW_AMOUNT_MINUTES
AS
SELECT AMOUNT_MINUTES 
FROM PACKAGE 
WHERE PACKAGE_ID = (
    SELECT PACKAGE_ID 
    FROM BALANCE 
    WHERE CUST_ID = (
        SELECT CUST_ID 
        FROM CUSTOMER 
        WHERE MSISDN = ?
    )
);

-- GET AMOUNT SMS BY MSISDN
CREATE PROCEDURE SHOW_AMOUNT_SMS 
AS
SELECT AMOUNT_SMS
FROM PACKAGE 
WHERE PACKAGE_ID = (
    SELECT PACKAGE_ID 
    FROM BALANCE 
    WHERE CUST_ID = (
        SELECT CUST_ID 
        FROM CUSTOMER 
        WHERE MSISDN = ?
    )
);

-- GET PACKAGE_NAME BY MSISDN
CREATE PROCEDURE SHOW_PACKAGE_NAME_BY_MSISDN
AS
SELECT PACKAGE_NAME  
FROM PACKAGE 
WHERE PACKAGE_ID = (
    SELECT PACKAGE_ID 
    FROM BALANCE 
    WHERE CUST_ID = (
        SELECT CUST_ID 
        FROM CUSTOMER 
        WHERE MSISDN = ?
    )
);

-- GET CUSTOMER INFO BY MSISDN
CREATE PROCEDURE  GET_CUSTOMER_INFO_BY_MSISDN 
AS
SELECT CUST_ID, MSISDN, NAME, SURNAME, EMAIL, SDATE, TC_NO
FROM CUSTOMER
WHERE MSISDN = ?;
